// swift-tools-version: 5.4

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Date Planner",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Date Planner",
            targets: ["App"],
            bundleIdentifier: "com.zhuhaoyu.student.dateplanner",
            teamIdentifier: "44BN78992X",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            supportedDeviceFamilies: [
                .pad,
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
            ],
            capabilities: [
                .camera(purposeString: "Eye trace"),
                .faceID(purposeString: "Eye trace"),
                .motion(purposeString: "Head trace"),
                .microphone(purposeString: "Speech"),
                .speechRecognition(purposeString: "Get the text")
            ],
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    dependencies: [
        .package(path: "Friendly"),
        .package(path: "SwiftUI-Introspect")
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                .product(name: "Friendly", package: "Friendly"),
                .product(name: "Introspect", package: "SwiftUI-Introspect")
            ],
            path: "App"
        )
    ]
)
